//! Tests for precedence logic in clap-layers

use clap::Parser;
use clap_layers::Layered;

fn cleanup_env_vars() {
    // Cleanup common env vars that might be set by other tests running in parallel
    unsafe {
        std::env::remove_var("port");
        std::env::remove_var("verbose");
        std::env::remove_var("MYAPP_PORT");
        std::env::remove_var("MYAPP_VERBOSE");
        std::env::remove_var("CLI_TEST_PORT");
        std::env::remove_var("CLI_TEST_VERBOSE");
    }
}

#[test]
fn test_default_values() {
    cleanup_env_vars();

    #[derive(Parser, Layered, Debug, PartialEq)]
    struct Config {
        #[arg(long, default_value_t = 3000)]
        port: u16,

        #[arg(long, default_value_t = false)]
        verbose: bool,
    }

    // When no args, env vars, or file are set, use defaults
    let cfg = Config::layered().unwrap();
    assert_eq!(cfg.port, 3000);
    assert!(!cfg.verbose);

    cleanup_env_vars();
}

#[test]
fn test_env_overrides_default() {
    // Set env var with field name in lowercase (as generated by the Layered macro)
    unsafe {
        std::env::set_var("PRECEDENCE_TEST_port", "8080");

        #[derive(Parser, Layered, Debug, PartialEq)]
        #[layered(env_prefix = "PRECEDENCE_TEST")]
        struct Config {
            #[arg(long, default_value_t = 3000)]
            port: u16,
        }

        let cfg = Config::layered().unwrap();

        std::env::remove_var("PRECEDENCE_TEST_port");

        assert_eq!(cfg.port, 8080); // Should be overridden from env
    }
}

#[test]
fn test_prefixed_env() {
    unsafe {
        std::env::set_var("PRECEDENCE_MYAPP_PORT", "9000");

        #[derive(Parser, Layered, Debug)]
        struct Config {
            #[arg(long, default_value_t = 3000)]
            port: u16,
        }

        let _cfg = Config::layered().unwrap();

        std::env::remove_var("PRECEDENCE_MYAPP_PORT");
    }
}

#[test]
fn test_file_overrides_default() {
    cleanup_env_vars();

    let file_path = "precedence_test_config.toml";
    std::fs::write(file_path, "port = 5000\n").expect("failed to write file");

    #[derive(Parser, Layered, Debug)]
    struct Config {
        #[arg(long, default_value_t = 3000)]
        port: u16,
    }

    let _cfg = Config::layered().unwrap();

    std::fs::remove_file(file_path).ok();
    cleanup_env_vars();
}

#[test]
fn test_cli_not_passed() {
    cleanup_env_vars();

    #[derive(Parser, Layered, Debug, PartialEq)]
    struct Config {
        #[arg(long, default_value_t = 3000)]
        port: u16,

        #[arg(long, default_value_t = false)]
        verbose: bool,
    }

    // When layered() parses from std::env::args(), no CLI args are provided
    // so it should use defaults
    let cfg = Config::layered().unwrap();
    assert_eq!(cfg.port, 3000);
    assert!(!cfg.verbose);

    cleanup_env_vars();
}
